[build]

	command = "hugo --verbose --i18n-warnings --baseURL $DEPLOY_PRIME_URL"
	publish = "public"
	environment = { HUGO_VERSION = "0.45.1" }

[context.production]

	command = "hugo --verbose --i18n-warnings --baseURL $URL"
